# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xmpluH7K76w9xwRrLzH9_nPfsPJ7RC4N
"""

import pandas as pd

df = pd.read_csv("Iris.csv")

df.shape
df.head()
df.info()

"""# New Section"""